/**
 * This file is auto-generated by scripts/lua-minifier.ts
 * Do not edit this file manually.
 */

export const slidingWindow =
    'local a=KEYS[1]local b=tonumber(ARGV[1])local c=tonumber(ARGV[2])local d=tonumber(ARGV[3])local e=ARGV[4]local f=b-c;redis.call("ZREMRANGEBYSCORE",a,0,f)local g=redis.call("ZCARD",a)if g>=d then local h=redis.call("ZRANGE",a,0,0,"WITHSCORES")[2]local i=(h or b)+c;return{0,0,i}end;redis.call("ZADD",a,b,b..":"..e)redis.call("PEXPIRE",a,c)local j=d-(g+1)local h=redis.call("ZRANGE",a,0,0,"WITHSCORES")[2]local i=(h or b)+c;return{1,j,i}'
